### ISSUE TITLE
Special character support

### ISSUE THREAD

**Issue by xiaohaozhi** [NyaShinn1204/Yoimi#7]
It seems that there is a problem with special character support.

URL：https://video.unext.jp/play/SID0164426/ED00607156
BanG Dream! 11th☆LIVE DAY1 : Poppin'Party×RAISE A SUILEN「GALAXY to GALAXY」

['Traceback (most recent call last):\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\unext_v2.py", line 441, in main_command\n    unext.Unext_decrypt.decrypt_content(license_key["video_key"], video_downloaded, video_downloaded.replace("_encrypted", ""), config)\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\utils\\unext.py", line 247, in decrypt_content\n    for line in process.stdout:\n                ^^^^^^^^^^^^^^\n', "UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 3: illegal multibyte sequence\n"]
['  File "I:\\Software\\Video_dl\\Yoimi\\ext\\unext_v2.py", line 441, in main_command\n    unext.Unext_decrypt.decrypt_content(license_key["video_key"], video_downloaded, video_downloaded.replace("_encrypted", ""), config)\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\utils\\unext.py", line 247, in decrypt_content\n    for line in process.stdout:\n                ^^^^^^^^^^^^^^\n']

I replaced mp4decrypt.exe and tried again.

['Traceback (most recent call last):\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\unext_v2.py", line 446, in main_command\n    result = unext_downloader.mux_episode(title_name_logger_video.replace("_encrypted",""), title_name_logger_audio.replace("_encrypted",""), os.path.join(config["directorys"]["Downloads"], title_name, title_name_logger+".mp4"), config, unixtime, title_name, int(message["duration"]))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\utils\\unext.py", line 585, in mux_episode\n    os.makedirs(os.path.join(config["directorys"]["Downloads"], title_name), exist_ok=True)\n', '  File "<frozen os>", line 225, in makedirs\n', 'NotADirectoryError: [WinError 267] 目录名称无效。: "./downloads\\\\BanG Dream! 11th☆LIVE DAY1 : Poppin\'Party×RAISE A SUILEN「GALAXY to GALAXY」"\n']
['  File "I:\\Software\\Video_dl\\Yoimi\\ext\\unext_v2.py", line 446, in main_command\n    result = unext_downloader.mux_episode(title_name_logger_video.replace("_encrypted",""), title_name_logger_audio.replace("_encrypted",""), os.path.join(config["directorys"]["Downloads"], title_name, title_name_logger+".mp4"), config, unixtime, title_name, int(message["duration"]))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\utils\\unext.py", line 585, in mux_episode\n    os.makedirs(os.path.join(config["directorys"]["Downloads"], title_name), exist_ok=True)\n', '  File "<frozen os>", line 225, in makedirs\n']

**Comment by NyaShinn1204** [comment]
Thanks report.
I'll aim to fix it in the next few days.

**Comment by NyaShinn1204** [comment]
I could not find much content on this side of the issue. Sorry.
I uploaded it as a uniform hot-fix-4. Please let me know if there is any problem.

**Comment by xiaohaozhi** [comment]
It's done with the replaced mp4decrypt.exe ( file from https://github.com/nilaoda/Blog/discussions/31#discussion-49475)
If use the origin exe ,still get the error  UnicodeDecodeError: 'gbk'.
Maybe you can try use temporary name and rename in the end, or use other mpd download tools.
https://github.com/nilaoda/N_m3u8DL-RE

**Comment by NyaShinn1204** [comment]
I checked here and found that the reason was that the encoding was not specified properly. Could you please try the following version for the sake of it?
[Yoimi-0.7-hot-fix-5.zip](https://github.com/user-attachments/files/18162727/Yoimi-0.7-hot-fix-5.zip)

**Comment by xiaohaozhi** [comment]
> I checked here and found that the reason was that the encoding was not specified properly. Could you please try the following version for the sake of it? [Yoimi-0.7-hot-fix-5.zip](https://github.com/user-attachments/files/18162727/Yoimi-0.7-hot-fix-5.zip)

still get error

['Traceback (most recent call last):\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\unext_v2.py", line 450, in main_command\n    unext.Unext_decrypt.decrypt_content(license_key["video_key"], video_downloaded, video_downloaded.replace("_encrypted", ""), config)\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\utils\\unext.py", line 247, in decrypt_content\n    for line in process.stdout:\n                ^^^^^^^^^^^^^^\n', '  File "<frozen codecs>", line 322, in decode\n', "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 3: invalid start byte\n"]
['  File "I:\\Software\\Video_dl\\Yoimi\\ext\\unext_v2.py", line 450, in main_command\n    unext.Unext_decrypt.decrypt_content(license_key["video_key"], video_downloaded, video_downloaded.replace("_encrypted", ""), config)\n', '  File "I:\\Software\\Video_dl\\Yoimi\\ext\\utils\\unext.py", line 247, in decrypt_content\n    for line in process.stdout:\n                ^^^^^^^^^^^^^^\n', '  File "<frozen codecs>", line 322, in decode\n']

**Comment by NyaShinn1204** [comment]
Uploaded mp4decrypt with replacement. (hot-fix-6)
